sudo: false
dist: xenial
language: java
jdk:
  # Install JDK8 for html5 validator.
  - oraclejdk8
env:
  - NODE_VERSION="6.9.5" PHANTOMJS_VERSION="2.1.1" PATH="$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
cache:
  directories:
    - travis_phantomjs
before_install: |
  nvm install $NODE_VERSION
  # Make sure cached PhantomJS is up to date
  if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
    rm -rf $PWD/travis_phantomjs
    mkdir -p $PWD/travis_phantomjs
    wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 \
      -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
    tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 \
      -C $PWD/travis_phantomjs
  fi
  phantomjs --version
install:
  # Disable the spinner; it looks bad on Travis.
  - npm config set spin false
  - npm install
  - pip install --user html5validator
script:
  - ./build
