#!/bin/bash

# Print commands.
set -x

# Exit on first error.
set -e

npm run travis

html5validator \
  --root ./app \
  --blacklist bower_components \
  --ignore-re 'Attribute "ng-[a-z-]+" not allowed' \
  --ignore 'Element "line-graph" not allowed' \
  --log INFO
